// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: mail.proto

package mailservice

import (
	"context"

	"simplemail/mail"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendMailRequest  = mail.SendMailRequest
	SendMailResponse = mail.SendMailResponse

	MailService interface {
		SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailResponse, error)
	}

	defaultMailService struct {
		cli zrpc.Client
	}
)

func NewMailService(cli zrpc.Client) MailService {
	return &defaultMailService{
		cli: cli,
	}
}

func (m *defaultMailService) SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailResponse, error) {
	client := mail.NewMailServiceClient(m.cli.Conn())
	return client.SendMail(ctx, in, opts...)
}
