// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: mail.proto

package server

import (
	"context"

	"simplemail/internal/logic"
	"simplemail/internal/svc"
	"simplemail/mail"
)

type MailServiceServer struct {
	svcCtx *svc.ServiceContext
	mail.UnimplementedMailServiceServer
}

func NewMailServiceServer(svcCtx *svc.ServiceContext) *MailServiceServer {
	return &MailServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MailServiceServer) SendMail(ctx context.Context, in *mail.SendMailRequest) (*mail.SendMailResponse, error) {
	l := logic.NewSendMailLogic(ctx, s.svcCtx)
	return l.SendMail(in)
}
